#!/bin/python3

# Fire, Logs, Water;
from random import randint
player = input ('fire (f), logs (l) or water (w)? :')

if player == 'f':
  print ('$$$', 'vs', end=' ')
elif player == 'l':
  print ('@@@', 'vs', end=' ')
elif player == 'w':
  print ('~~~', 'vs', end=' ')
  
chosen = randint(1,3)

#print(chosen)

if chosen == 1:
  computer = 'f'
  print('$$$')
  
elif chosen == 2:
  computer = 'l'
  print('@@@')
  
else:
  computer = 'w'
  print('~~~')
  
#print(computer)

if player == computer:
  print('DRAW!')
  
elif player == 'f' and computer == 'w':
  print('Computer wins')
  
elif player == 'f' and computer == 'l':
  print('Player wins')
  
elif player == 'l' and computer == 'f':
  print('Computer wins')
  
elif player == 'l' and computer == 'w':
  print('Player wins')
  
elif player == 'w' and computer == 'l':
  print('Computer wins')
  
elif player == 'w' and computer == 'f':
  print('Player wins')
