#!/bin/python3
alphabet = 'abcdefghijklmnopqrstuvwxyz'
newMessage = ''
message = input ('Please enter a message: ')
yourKey = input ('Enter your own key (choose from 1 to 25): ')
key = int(yourKey)

for character in message:
  if character in alphabet:
    position = alphabet.find(character)
    newPosition = (position + key) % 26
    newCharacter = alphabet[newPosition]
    newMessage += newCharacter
  else:
      newMessage += character
  
print ('Your new message is:', newMessage)
